//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelVaksinClient.ServiceSemuaData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Akun", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Akun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rollField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roll {
            get {
                return this.rollField;
            }
            set {
                if ((object.ReferenceEquals(this.rollField, value) != true)) {
                    this.rollField = value;
                    this.RaisePropertyChanged("roll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vaksin", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Vaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_vaksin {
            get {
                return this.ID_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_vaksinField, value) != true)) {
                    this.ID_vaksinField = value;
                    this.RaisePropertyChanged("ID_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vaksin_Veried", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Vaksin_Veried : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_perawatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_vaksin {
            get {
                return this.ID_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_vaksinField, value) != true)) {
                    this.ID_vaksinField = value;
                    this.RaisePropertyChanged("ID_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIK {
            get {
                return this.NIKField;
            }
            set {
                if ((object.ReferenceEquals(this.NIKField, value) != true)) {
                    this.NIKField = value;
                    this.RaisePropertyChanged("NIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_perawat {
            get {
                return this.nama_perawatField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_perawatField, value) != true)) {
                    this.nama_perawatField = value;
                    this.RaisePropertyChanged("nama_perawat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Regis_Vaksin", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Regis_Vaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_vaksin {
            get {
                return this.ID_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_vaksinField, value) != true)) {
                    this.ID_vaksinField = value;
                    this.RaisePropertyChanged("ID_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Penduduk", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Penduduk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jenis_kelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> umurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIK {
            get {
                return this.NIKField;
            }
            set {
                if ((object.ReferenceEquals(this.NIKField, value) != true)) {
                    this.NIKField = value;
                    this.RaisePropertyChanged("NIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jenis_kelamin {
            get {
                return this.jenis_kelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.jenis_kelaminField, value) != true)) {
                    this.jenis_kelaminField = value;
                    this.RaisePropertyChanged("jenis_kelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profil {
            get {
                return this.profilField;
            }
            set {
                if ((object.ReferenceEquals(this.profilField, value) != true)) {
                    this.profilField = value;
                    this.RaisePropertyChanged("profil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> umur {
            get {
                return this.umurField;
            }
            set {
                if ((this.umurField.Equals(value) != true)) {
                    this.umurField = value;
                    this.RaisePropertyChanged("umur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSemuaData.IAllData")]
    public interface IAllData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllAkun", ReplyAction="http://tempuri.org/IAllData/getAllAkunResponse")]
        DelVaksinClient.ServiceSemuaData.Akun[] getAllAkun();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllAkun", ReplyAction="http://tempuri.org/IAllData/getAllAkunResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Akun[]> getAllAkunAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllVaksin", ReplyAction="http://tempuri.org/IAllData/getAllVaksinResponse")]
        DelVaksinClient.ServiceSemuaData.Vaksin[] getAllVaksin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllVaksin", ReplyAction="http://tempuri.org/IAllData/getAllVaksinResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin[]> getAllVaksinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllVaksin_Veried", ReplyAction="http://tempuri.org/IAllData/getAllVaksin_VeriedResponse")]
        DelVaksinClient.ServiceSemuaData.Vaksin_Veried[] getAllVaksin_Veried();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllVaksin_Veried", ReplyAction="http://tempuri.org/IAllData/getAllVaksin_VeriedResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin_Veried[]> getAllVaksin_VeriedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllRegis_Vaksin", ReplyAction="http://tempuri.org/IAllData/getAllRegis_VaksinResponse")]
        DelVaksinClient.ServiceSemuaData.Regis_Vaksin[] getAllRegis_Vaksin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllRegis_Vaksin", ReplyAction="http://tempuri.org/IAllData/getAllRegis_VaksinResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Regis_Vaksin[]> getAllRegis_VaksinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllPenduduk", ReplyAction="http://tempuri.org/IAllData/getAllPendudukResponse")]
        DelVaksinClient.ServiceSemuaData.Penduduk[] getAllPenduduk();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getAllPenduduk", ReplyAction="http://tempuri.org/IAllData/getAllPendudukResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Penduduk[]> getAllPendudukAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdVaksin", ReplyAction="http://tempuri.org/IAllData/getByIdVaksinResponse")]
        DelVaksinClient.ServiceSemuaData.Vaksin getByIdVaksin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdVaksin", ReplyAction="http://tempuri.org/IAllData/getByIdVaksinResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin> getByIdVaksinAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdVaksin_Veried", ReplyAction="http://tempuri.org/IAllData/getByIdVaksin_VeriedResponse")]
        DelVaksinClient.ServiceSemuaData.Vaksin_Veried getByIdVaksin_Veried(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdVaksin_Veried", ReplyAction="http://tempuri.org/IAllData/getByIdVaksin_VeriedResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin_Veried> getByIdVaksin_VeriedAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdRegis_Vaksin", ReplyAction="http://tempuri.org/IAllData/getByIdRegis_VaksinResponse")]
        DelVaksinClient.ServiceSemuaData.Regis_Vaksin getByIdRegis_Vaksin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdRegis_Vaksin", ReplyAction="http://tempuri.org/IAllData/getByIdRegis_VaksinResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Regis_Vaksin> getByIdRegis_VaksinAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdPenduduk", ReplyAction="http://tempuri.org/IAllData/getByIdPendudukResponse")]
        DelVaksinClient.ServiceSemuaData.Penduduk getByIdPenduduk(string NIK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllData/getByIdPenduduk", ReplyAction="http://tempuri.org/IAllData/getByIdPendudukResponse")]
        System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Penduduk> getByIdPendudukAsync(string NIK);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllDataChannel : DelVaksinClient.ServiceSemuaData.IAllData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllDataClient : System.ServiceModel.ClientBase<DelVaksinClient.ServiceSemuaData.IAllData>, DelVaksinClient.ServiceSemuaData.IAllData {
        
        public AllDataClient() {
        }
        
        public AllDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DelVaksinClient.ServiceSemuaData.Akun[] getAllAkun() {
            return base.Channel.getAllAkun();
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Akun[]> getAllAkunAsync() {
            return base.Channel.getAllAkunAsync();
        }
        
        public DelVaksinClient.ServiceSemuaData.Vaksin[] getAllVaksin() {
            return base.Channel.getAllVaksin();
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin[]> getAllVaksinAsync() {
            return base.Channel.getAllVaksinAsync();
        }
        
        public DelVaksinClient.ServiceSemuaData.Vaksin_Veried[] getAllVaksin_Veried() {
            return base.Channel.getAllVaksin_Veried();
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin_Veried[]> getAllVaksin_VeriedAsync() {
            return base.Channel.getAllVaksin_VeriedAsync();
        }
        
        public DelVaksinClient.ServiceSemuaData.Regis_Vaksin[] getAllRegis_Vaksin() {
            return base.Channel.getAllRegis_Vaksin();
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Regis_Vaksin[]> getAllRegis_VaksinAsync() {
            return base.Channel.getAllRegis_VaksinAsync();
        }
        
        public DelVaksinClient.ServiceSemuaData.Penduduk[] getAllPenduduk() {
            return base.Channel.getAllPenduduk();
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Penduduk[]> getAllPendudukAsync() {
            return base.Channel.getAllPendudukAsync();
        }
        
        public DelVaksinClient.ServiceSemuaData.Vaksin getByIdVaksin(string id) {
            return base.Channel.getByIdVaksin(id);
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin> getByIdVaksinAsync(string id) {
            return base.Channel.getByIdVaksinAsync(id);
        }
        
        public DelVaksinClient.ServiceSemuaData.Vaksin_Veried getByIdVaksin_Veried(string id) {
            return base.Channel.getByIdVaksin_Veried(id);
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Vaksin_Veried> getByIdVaksin_VeriedAsync(string id) {
            return base.Channel.getByIdVaksin_VeriedAsync(id);
        }
        
        public DelVaksinClient.ServiceSemuaData.Regis_Vaksin getByIdRegis_Vaksin(string id) {
            return base.Channel.getByIdRegis_Vaksin(id);
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Regis_Vaksin> getByIdRegis_VaksinAsync(string id) {
            return base.Channel.getByIdRegis_VaksinAsync(id);
        }
        
        public DelVaksinClient.ServiceSemuaData.Penduduk getByIdPenduduk(string NIK) {
            return base.Channel.getByIdPenduduk(NIK);
        }
        
        public System.Threading.Tasks.Task<DelVaksinClient.ServiceSemuaData.Penduduk> getByIdPendudukAsync(string NIK) {
            return base.Channel.getByIdPendudukAsync(NIK);
        }
    }
}
