//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelVaksinClient.ServiceSemuaFungsi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Penduduk", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Penduduk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jenis_kelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> umurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIK {
            get {
                return this.NIKField;
            }
            set {
                if ((object.ReferenceEquals(this.NIKField, value) != true)) {
                    this.NIKField = value;
                    this.RaisePropertyChanged("NIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jenis_kelamin {
            get {
                return this.jenis_kelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.jenis_kelaminField, value) != true)) {
                    this.jenis_kelaminField = value;
                    this.RaisePropertyChanged("jenis_kelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profil {
            get {
                return this.profilField;
            }
            set {
                if ((object.ReferenceEquals(this.profilField, value) != true)) {
                    this.profilField = value;
                    this.RaisePropertyChanged("profil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> umur {
            get {
                return this.umurField;
            }
            set {
                if ((this.umurField.Equals(value) != true)) {
                    this.umurField = value;
                    this.RaisePropertyChanged("umur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vaksin", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Vaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_vaksin {
            get {
                return this.ID_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_vaksinField, value) != true)) {
                    this.ID_vaksinField = value;
                    this.RaisePropertyChanged("ID_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vaksin_Veried", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Vaksin_Veried : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_perawatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_vaksin {
            get {
                return this.ID_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_vaksinField, value) != true)) {
                    this.ID_vaksinField = value;
                    this.RaisePropertyChanged("ID_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIK {
            get {
                return this.NIKField;
            }
            set {
                if ((object.ReferenceEquals(this.NIKField, value) != true)) {
                    this.NIKField = value;
                    this.RaisePropertyChanged("NIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_perawat {
            get {
                return this.nama_perawatField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_perawatField, value) != true)) {
                    this.nama_perawatField = value;
                    this.RaisePropertyChanged("nama_perawat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSemuaFungsi.IAllFunc")]
    public interface IAllFunc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/Register", ReplyAction="http://tempuri.org/IAllFunc/RegisterResponse")]
        bool Register(DelVaksinClient.ServiceSemuaFungsi.Penduduk penduduk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/Register", ReplyAction="http://tempuri.org/IAllFunc/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(DelVaksinClient.ServiceSemuaFungsi.Penduduk penduduk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/terimaVaksin", ReplyAction="http://tempuri.org/IAllFunc/terimaVaksinResponse")]
        bool terimaVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/terimaVaksin", ReplyAction="http://tempuri.org/IAllFunc/terimaVaksinResponse")]
        System.Threading.Tasks.Task<bool> terimaVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/tolakVaksin", ReplyAction="http://tempuri.org/IAllFunc/tolakVaksinResponse")]
        bool tolakVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/tolakVaksin", ReplyAction="http://tempuri.org/IAllFunc/tolakVaksinResponse")]
        System.Threading.Tasks.Task<bool> tolakVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/gunakanVaksin", ReplyAction="http://tempuri.org/IAllFunc/gunakanVaksinResponse")]
        bool gunakanVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/gunakanVaksin", ReplyAction="http://tempuri.org/IAllFunc/gunakanVaksinResponse")]
        System.Threading.Tasks.Task<bool> gunakanVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/tambahVaksin", ReplyAction="http://tempuri.org/IAllFunc/tambahVaksinResponse")]
        bool tambahVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/tambahVaksin", ReplyAction="http://tempuri.org/IAllFunc/tambahVaksinResponse")]
        System.Threading.Tasks.Task<bool> tambahVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/editVaksin", ReplyAction="http://tempuri.org/IAllFunc/editVaksinResponse")]
        bool editVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/editVaksin", ReplyAction="http://tempuri.org/IAllFunc/editVaksinResponse")]
        System.Threading.Tasks.Task<bool> editVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/hapusVaksin", ReplyAction="http://tempuri.org/IAllFunc/hapusVaksinResponse")]
        bool hapusVaksin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/hapusVaksin", ReplyAction="http://tempuri.org/IAllFunc/hapusVaksinResponse")]
        System.Threading.Tasks.Task<bool> hapusVaksinAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/kirimVaksin", ReplyAction="http://tempuri.org/IAllFunc/kirimVaksinResponse")]
        bool kirimVaksin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/kirimVaksin", ReplyAction="http://tempuri.org/IAllFunc/kirimVaksinResponse")]
        System.Threading.Tasks.Task<bool> kirimVaksinAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/bagikanVaksinId", ReplyAction="http://tempuri.org/IAllFunc/bagikanVaksinIdResponse")]
        bool bagikanVaksinId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/bagikanVaksinId", ReplyAction="http://tempuri.org/IAllFunc/bagikanVaksinIdResponse")]
        System.Threading.Tasks.Task<bool> bagikanVaksinIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/bagikanVaksinAll", ReplyAction="http://tempuri.org/IAllFunc/bagikanVaksinAllResponse")]
        bool bagikanVaksinAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/bagikanVaksinAll", ReplyAction="http://tempuri.org/IAllFunc/bagikanVaksinAllResponse")]
        System.Threading.Tasks.Task<bool> bagikanVaksinAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/daftarVaksin", ReplyAction="http://tempuri.org/IAllFunc/daftarVaksinResponse")]
        bool daftarVaksin(string NIK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/daftarVaksin", ReplyAction="http://tempuri.org/IAllFunc/daftarVaksinResponse")]
        System.Threading.Tasks.Task<bool> daftarVaksinAsync(string NIK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/gunakanVaksinPenduduk", ReplyAction="http://tempuri.org/IAllFunc/gunakanVaksinPendudukResponse")]
        bool gunakanVaksinPenduduk(DelVaksinClient.ServiceSemuaFungsi.Vaksin_Veried vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/gunakanVaksinPenduduk", ReplyAction="http://tempuri.org/IAllFunc/gunakanVaksinPendudukResponse")]
        System.Threading.Tasks.Task<bool> gunakanVaksinPendudukAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin_Veried vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/vaksinSudahTerpakai", ReplyAction="http://tempuri.org/IAllFunc/vaksinSudahTerpakaiResponse")]
        bool vaksinSudahTerpakai(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/vaksinSudahTerpakai", ReplyAction="http://tempuri.org/IAllFunc/vaksinSudahTerpakaiResponse")]
        System.Threading.Tasks.Task<bool> vaksinSudahTerpakaiAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/balikStatusPenduduk", ReplyAction="http://tempuri.org/IAllFunc/balikStatusPendudukResponse")]
        bool balikStatusPenduduk(string NIK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/balikStatusPenduduk", ReplyAction="http://tempuri.org/IAllFunc/balikStatusPendudukResponse")]
        System.Threading.Tasks.Task<bool> balikStatusPendudukAsync(string NIK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/ubahDataPenduduk", ReplyAction="http://tempuri.org/IAllFunc/ubahDataPendudukResponse")]
        bool ubahDataPenduduk(string nik, string nama, int umur, string alamat, string j_kel, string profil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/ubahDataPenduduk", ReplyAction="http://tempuri.org/IAllFunc/ubahDataPendudukResponse")]
        System.Threading.Tasks.Task<bool> ubahDataPendudukAsync(string nik, string nama, int umur, string alamat, string j_kel, string profil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/ubahPasswordPenduduk", ReplyAction="http://tempuri.org/IAllFunc/ubahPasswordPendudukResponse")]
        bool ubahPasswordPenduduk(string nik, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllFunc/ubahPasswordPenduduk", ReplyAction="http://tempuri.org/IAllFunc/ubahPasswordPendudukResponse")]
        System.Threading.Tasks.Task<bool> ubahPasswordPendudukAsync(string nik, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllFuncChannel : DelVaksinClient.ServiceSemuaFungsi.IAllFunc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllFuncClient : System.ServiceModel.ClientBase<DelVaksinClient.ServiceSemuaFungsi.IAllFunc>, DelVaksinClient.ServiceSemuaFungsi.IAllFunc {
        
        public AllFuncClient() {
        }
        
        public AllFuncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllFuncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllFuncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllFuncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(DelVaksinClient.ServiceSemuaFungsi.Penduduk penduduk) {
            return base.Channel.Register(penduduk);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(DelVaksinClient.ServiceSemuaFungsi.Penduduk penduduk) {
            return base.Channel.RegisterAsync(penduduk);
        }
        
        public bool terimaVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.terimaVaksin(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> terimaVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.terimaVaksinAsync(vaksin);
        }
        
        public bool tolakVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.tolakVaksin(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> tolakVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.tolakVaksinAsync(vaksin);
        }
        
        public bool gunakanVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.gunakanVaksin(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> gunakanVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.gunakanVaksinAsync(vaksin);
        }
        
        public bool tambahVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.tambahVaksin(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> tambahVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.tambahVaksinAsync(vaksin);
        }
        
        public bool editVaksin(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.editVaksin(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> editVaksinAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin vaksin) {
            return base.Channel.editVaksinAsync(vaksin);
        }
        
        public bool hapusVaksin(string id) {
            return base.Channel.hapusVaksin(id);
        }
        
        public System.Threading.Tasks.Task<bool> hapusVaksinAsync(string id) {
            return base.Channel.hapusVaksinAsync(id);
        }
        
        public bool kirimVaksin(string id) {
            return base.Channel.kirimVaksin(id);
        }
        
        public System.Threading.Tasks.Task<bool> kirimVaksinAsync(string id) {
            return base.Channel.kirimVaksinAsync(id);
        }
        
        public bool bagikanVaksinId(string id) {
            return base.Channel.bagikanVaksinId(id);
        }
        
        public System.Threading.Tasks.Task<bool> bagikanVaksinIdAsync(string id) {
            return base.Channel.bagikanVaksinIdAsync(id);
        }
        
        public bool bagikanVaksinAll() {
            return base.Channel.bagikanVaksinAll();
        }
        
        public System.Threading.Tasks.Task<bool> bagikanVaksinAllAsync() {
            return base.Channel.bagikanVaksinAllAsync();
        }
        
        public bool daftarVaksin(string NIK) {
            return base.Channel.daftarVaksin(NIK);
        }
        
        public System.Threading.Tasks.Task<bool> daftarVaksinAsync(string NIK) {
            return base.Channel.daftarVaksinAsync(NIK);
        }
        
        public bool gunakanVaksinPenduduk(DelVaksinClient.ServiceSemuaFungsi.Vaksin_Veried vaksin) {
            return base.Channel.gunakanVaksinPenduduk(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> gunakanVaksinPendudukAsync(DelVaksinClient.ServiceSemuaFungsi.Vaksin_Veried vaksin) {
            return base.Channel.gunakanVaksinPendudukAsync(vaksin);
        }
        
        public bool vaksinSudahTerpakai(string id) {
            return base.Channel.vaksinSudahTerpakai(id);
        }
        
        public System.Threading.Tasks.Task<bool> vaksinSudahTerpakaiAsync(string id) {
            return base.Channel.vaksinSudahTerpakaiAsync(id);
        }
        
        public bool balikStatusPenduduk(string NIK) {
            return base.Channel.balikStatusPenduduk(NIK);
        }
        
        public System.Threading.Tasks.Task<bool> balikStatusPendudukAsync(string NIK) {
            return base.Channel.balikStatusPendudukAsync(NIK);
        }
        
        public bool ubahDataPenduduk(string nik, string nama, int umur, string alamat, string j_kel, string profil) {
            return base.Channel.ubahDataPenduduk(nik, nama, umur, alamat, j_kel, profil);
        }
        
        public System.Threading.Tasks.Task<bool> ubahDataPendudukAsync(string nik, string nama, int umur, string alamat, string j_kel, string profil) {
            return base.Channel.ubahDataPendudukAsync(nik, nama, umur, alamat, j_kel, profil);
        }
        
        public bool ubahPasswordPenduduk(string nik, string password) {
            return base.Channel.ubahPasswordPenduduk(nik, password);
        }
        
        public System.Threading.Tasks.Task<bool> ubahPasswordPendudukAsync(string nik, string password) {
            return base.Channel.ubahPasswordPendudukAsync(nik, password);
        }
    }
}
