//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelVaksin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEL_VAKSINEntities : DbContext
    {
        public DEL_VAKSINEntities()
            : base("name=DEL_VAKSINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akun> Akuns { get; set; }
        public virtual DbSet<Penduduk> Penduduks { get; set; }
        public virtual DbSet<Regis_Vaksin> Regis_Vaksin { get; set; }
        public virtual DbSet<Vaksin> Vaksins { get; set; }
        public virtual DbSet<Vaksin_Veried> Vaksin_Veried { get; set; }
    }
}
