//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelVaksin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penduduk
    {
        public string NIK { get; set; }
        public string nama { get; set; }
        public Nullable<int> umur { get; set; }
        public string alamat { get; set; }
        public string jenis_kelamin { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string profil { get; set; }
        public Nullable<int> status { get; set; }
    }
}
