//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelVaksinClient.ServicePemerintah {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Penduduk", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Penduduk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jenis_kelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> umurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIK {
            get {
                return this.NIKField;
            }
            set {
                if ((object.ReferenceEquals(this.NIKField, value) != true)) {
                    this.NIKField = value;
                    this.RaisePropertyChanged("NIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jenis_kelamin {
            get {
                return this.jenis_kelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.jenis_kelaminField, value) != true)) {
                    this.jenis_kelaminField = value;
                    this.RaisePropertyChanged("jenis_kelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profil {
            get {
                return this.profilField;
            }
            set {
                if ((object.ReferenceEquals(this.profilField, value) != true)) {
                    this.profilField = value;
                    this.RaisePropertyChanged("profil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> umur {
            get {
                return this.umurField;
            }
            set {
                if ((this.umurField.Equals(value) != true)) {
                    this.umurField = value;
                    this.RaisePropertyChanged("umur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePemerintah.ISPemerintah")]
    public interface ISPemerintah {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPemerintah/confirNik", ReplyAction="http://tempuri.org/ISPemerintah/confirNikResponse")]
        bool confirNik(DelVaksinClient.ServicePemerintah.Penduduk penduduk, string tipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPemerintah/confirNik", ReplyAction="http://tempuri.org/ISPemerintah/confirNikResponse")]
        System.Threading.Tasks.Task<bool> confirNikAsync(DelVaksinClient.ServicePemerintah.Penduduk penduduk, string tipe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISPemerintahChannel : DelVaksinClient.ServicePemerintah.ISPemerintah, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPemerintahClient : System.ServiceModel.ClientBase<DelVaksinClient.ServicePemerintah.ISPemerintah>, DelVaksinClient.ServicePemerintah.ISPemerintah {
        
        public SPemerintahClient() {
        }
        
        public SPemerintahClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPemerintahClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPemerintahClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPemerintahClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool confirNik(DelVaksinClient.ServicePemerintah.Penduduk penduduk, string tipe) {
            return base.Channel.confirNik(penduduk, tipe);
        }
        
        public System.Threading.Tasks.Task<bool> confirNikAsync(DelVaksinClient.ServicePemerintah.Penduduk penduduk, string tipe) {
            return base.Channel.confirNikAsync(penduduk, tipe);
        }
    }
}
