//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelVaksinClient.ServiceBPOM {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vaksin", Namespace="http://schemas.datacontract.org/2004/07/DelVaksin")]
    [System.SerializableAttribute()]
    public partial class Vaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_vaksin {
            get {
                return this.ID_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_vaksinField, value) != true)) {
                    this.ID_vaksinField = value;
                    this.RaisePropertyChanged("ID_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBPOM.ISBPOM")]
    public interface ISBPOM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISBPOM/RegisVaksin", ReplyAction="http://tempuri.org/ISBPOM/RegisVaksinResponse")]
        bool RegisVaksin(DelVaksinClient.ServiceBPOM.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISBPOM/RegisVaksin", ReplyAction="http://tempuri.org/ISBPOM/RegisVaksinResponse")]
        System.Threading.Tasks.Task<bool> RegisVaksinAsync(DelVaksinClient.ServiceBPOM.Vaksin vaksin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISBPOM/ReportVaksinSampai", ReplyAction="http://tempuri.org/ISBPOM/ReportVaksinSampaiResponse")]
        bool ReportVaksinSampai(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISBPOM/ReportVaksinSampai", ReplyAction="http://tempuri.org/ISBPOM/ReportVaksinSampaiResponse")]
        System.Threading.Tasks.Task<bool> ReportVaksinSampaiAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISBPOM/ReportVaksindiGunakan", ReplyAction="http://tempuri.org/ISBPOM/ReportVaksindiGunakanResponse")]
        bool ReportVaksindiGunakan(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISBPOM/ReportVaksindiGunakan", ReplyAction="http://tempuri.org/ISBPOM/ReportVaksindiGunakanResponse")]
        System.Threading.Tasks.Task<bool> ReportVaksindiGunakanAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISBPOMChannel : DelVaksinClient.ServiceBPOM.ISBPOM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SBPOMClient : System.ServiceModel.ClientBase<DelVaksinClient.ServiceBPOM.ISBPOM>, DelVaksinClient.ServiceBPOM.ISBPOM {
        
        public SBPOMClient() {
        }
        
        public SBPOMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SBPOMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SBPOMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SBPOMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisVaksin(DelVaksinClient.ServiceBPOM.Vaksin vaksin) {
            return base.Channel.RegisVaksin(vaksin);
        }
        
        public System.Threading.Tasks.Task<bool> RegisVaksinAsync(DelVaksinClient.ServiceBPOM.Vaksin vaksin) {
            return base.Channel.RegisVaksinAsync(vaksin);
        }
        
        public bool ReportVaksinSampai(string id) {
            return base.Channel.ReportVaksinSampai(id);
        }
        
        public System.Threading.Tasks.Task<bool> ReportVaksinSampaiAsync(string id) {
            return base.Channel.ReportVaksinSampaiAsync(id);
        }
        
        public bool ReportVaksindiGunakan(string id) {
            return base.Channel.ReportVaksindiGunakan(id);
        }
        
        public System.Threading.Tasks.Task<bool> ReportVaksindiGunakanAsync(string id) {
            return base.Channel.ReportVaksindiGunakanAsync(id);
        }
    }
}
